name: register
networks:
  common: {}
services:
  common:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - common
    volumes:
      - ./.rubocop.yml:/home/x/r/.rubocop.yml
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./bin:/home/x/r/bin
      - ./lib:/home/x/r/lib
      - ./register_common.gemspec:/home/x/r/register_common.gemspec
      - ./spec:/home/x/r/spec
version: "3.8"
